

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Saman
 */
public class projectView extends javax.swing.JFrame {

    private Object statusTxt;

    /**
     * Creates new form projectView
     */
    public projectView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblProjectId = new javax.swing.JLabel();
        lblProjectName = new javax.swing.JLabel();
        lblProjectCodt = new javax.swing.JLabel();
        txtpId = new javax.swing.JTextField();
        txtpName = new javax.swing.JTextField();
        txtpCost = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnSearchById = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblmessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PROJECT DETAILS");

        lblProjectId.setText("Project ID");

        lblProjectName.setText("Project Name");

        lblProjectCodt.setText("Project Cost");

        txtpId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpIdActionPerformed(evt);
            }
        });

        txtpCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpCostActionPerformed(evt);
            }
        });

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSearchById.setText("SEARCH BY ID");
        btnSearchById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByIdActionPerformed(evt);
            }
        });

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProjectCodt)
                            .addComponent(lblProjectName)
                            .addComponent(lblProjectId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtpId)
                            .addComponent(txtpName)
                            .addComponent(txtpCost, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))))
                .addGap(434, 434, 434))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(btnAdd)
                        .addGap(45, 45, 45)
                        .addComponent(btnSearchById)
                        .addGap(39, 39, 39)
                        .addComponent(btnUpdate)
                        .addGap(44, 44, 44)
                        .addComponent(btnDelete)
                        .addGap(38, 38, 38)
                        .addComponent(btnClear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(lblmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjectId)
                    .addComponent(txtpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjectName)
                    .addComponent(txtpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjectCodt)
                    .addComponent(txtpCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(lblmessage)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnSearchById)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addContainerGap(213, Short.MAX_VALUE))
        );

        btnAdd.getAccessibleContext().setAccessibleName("btnAdd");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpCostActionPerformed

    private void btnSearchByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByIdActionPerformed
        if("".equals(txtpId.getText())){
            lblmessage.setText("Project Id cannot be null");
        }
        else{
             
            ProjectManager pm = new ProjectManager();
            Project p=pm.searchById(Integer.parseInt(txtpId.getText().trim()));
            
            txtpName.setText(p.getpname());
            txtpCost.setText(Double.toString(p.getpcost()));   
        }
    }//GEN-LAST:event_btnSearchByIdActionPerformed

    private void txtpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpIdActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        if("".equals(txtpId.getText())){
            
            lblmessage.setText("Project Id cannot be null");
            
        }
        else{
          Project project= new Project(Integer.parseInt(txtpId.getText().trim()),txtpName.getText().trim(),Float.parseFloat(txtpCost.getText().trim()));
          ProjectManager pm = new ProjectManager();
          boolean states = pm.insert(project);
          
          if(states == true){
             
              lblmessage.setText("Data inserted successfully");
          }
          else{
              lblmessage.setText("Data not inserted. Try Again!");
          }  
        }     
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
      if("".equals(txtpId.getText())){
           
          lblmessage.setText("Project Id cannot be null");
          
        }
      else{
        Project project = new Project(Integer.parseInt(txtpId.getText().trim()),txtpName.getText().trim(),Float.parseFloat(txtpCost.getText().trim()));
        ProjectManager pm = new ProjectManager();
        boolean states = pm.update(project); 
        
        if(states == true){
            
           lblmessage.setText("Data updated successfully"); 
        }
        else{
            
            lblmessage.setText("Data not updated. Try Again!");
            
        }
      }
      
      
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if("".equals(txtpId.getText())){
            
            lblmessage.setText("Project Id cannot be null");
            
        }
        else{
            ProjectManager pm = new ProjectManager();
            boolean states = pm.delete(Integer.parseInt(txtpId.getText())); 
            
            if(states == true){
                
                lblmessage.setText("Data deleted successfully");
                
            }
            else{
                
                lblmessage.setText("Data not deleted. Try Again!");
                
            }
        }
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtpId.setText(null);
        txtpName.setText(null);
        txtpCost.setText(null);
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(projectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(projectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(projectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(projectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new projectView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearchById;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblProjectCodt;
    private javax.swing.JLabel lblProjectId;
    private javax.swing.JLabel lblProjectName;
    private javax.swing.JLabel lblmessage;
    private javax.swing.JTextField txtpCost;
    private javax.swing.JTextField txtpId;
    private javax.swing.JTextField txtpName;
    // End of variables declaration//GEN-END:variables
}
